# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GoogleStreetViewLayer
                                 A QGIS plugin
 A QGIS plugin that uses your road layer, and creates a layer or table with the most recent Google Street View capture data. Google API Key required!
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-04
        copyright            : (C) 2022 by Nathan Saylor
        email                : gisn8@yahoo.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'Nathan Saylor'
__date__ = '2022-04-04'
__copyright__ = '(C) 2022 by Nathan Saylor'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GoogleStreetViewLayer class from file GoogleStreetViewLayer.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .google_street_view_layer import GoogleStreetViewLayerPlugin
    return GoogleStreetViewLayerPlugin(iface)
